export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const ADD_CHANNEL = "ADD_CHANNEL";
export const FETCH_CHANNEL = "FETCH_CHANNEL";
export const FETCH_CHANNEL_DETAIL = "FETCH_CHANNEL_DETAIL";
export const FETCH_MSGS = "FETCH_MSGS";
export const ADD_MSG = "ADD_MSG";
export const FILTER_CHANNELS = "FILTER_CHANNELS";
