export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const FETCH_CHANNELS = "FETCH_CHANNELS";
export const FETCH_SELECTED_CHANNELS = "FETCH_SELECTED_CHANNELS";
export const POST_CHANNEL = "POST_CHANNEL";
export const POST_ON_CHANNEL = "POST_ON_CHANNEL";
export const FILTER_CHANNELS = "FILTER_CHANNELS";
export const SET_LOADING = "SET_LOADING";
